Deflake test_saverestore_backfill_only (#933)
Test was intermittently failing with
```
assert i["search_rdb_save_keys"] == 0
AssertionError: assert 13 == 0
```
The test verifies when an index is still backfilling with zero progress,
RDB save writes 0 keys and 0 mutation entries. Above failure shows that
sometimes it ended up performing the backfilling the keys.
`block_mutation_queue` pausepoint used in the test only blocks worker
threads (ProcessSingleMutationAsync) and not the main thread where a
cron callbakc peroforms Backfill (`SchemaManager::OnServerCronCallback`
→ `PerformBackfill` → `BackfillScanCallback` →
`ProcessKeyspaceNotification` → `ProcessMutation` → `UpdateDbInfoKey`
) and populates `search_rdb_save_keys` causing the test to fail. I
suppose original intention was to Stop backfill and verify if RDB save
writes 0 keys and 0 mutation entries. Using StopBAckfill debug variable
(as seen in other test in this file) so we make sure save on an index
that's not done backfilling.

Signed-off-by: Aksha Thakkar <thaakb@amazon.com>
Co-authored-by: Aksha Thakkar <thaakb@amazon.com>
(cherry picked from commit f85c179b3ee2cd9048db2780c4f00085bdbe3a3e)